name: Deploy to PyPi

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'pyproject.toml' # we consider version has been bumped
jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch the repository
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12' 
      
      - name: Prepare Python Environment
        run: pip install poetry && poetry install && poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}

      - name: Run Pytests
        run: poetry run pytest tests/ -s -q -p no:warnings
        env:
          LXNS_DEVELOPER_TOKEN: ${{ secrets.LXNS_DEVELOPER_TOKEN }}
          DIVINGFISH_DEVELOPER_TOKEN: ${{ secrets.DIVINGFISH_DEVELOPER_TOKEN }}

      - name: Deploy to PyPi
        run: poetry build && poetry publish